modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/NadirKhoulali/Ultimate-Auction-System-UAS/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/NadirKhoulali/Ultimate-Auction-System-UAS/wiki"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ultimatebankingsystem"
type = "required"
reason = "UAS settles auction payments through the Ultimate Banking System API."
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"
